import { Tlevel } from '../../types';
import tags from './tags';

const levels: Tlevel[] = [
    {
        nameOfLevel: 'Level 1',
        number: 1,
        whattodo: 'Select Jerry mice',
        selector: 'jerry',
        rightAnswer: 'jerry',
        anotherPossibleAnwers: ['*', 'jerry:empty', ':nth-child(1n)', ':nth-child(1n+1)'],
        htmlBlockInnerTags: [
            tags.jerry.lineBreak,
            `<div id='0' class='level_code jerry_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.oneTag,
            tags.jerry.lineBreak,
            '</div>',
            `<div id='1' class='level_code jerry_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.oneTag,
            tags.jerry.lineBreak,
            '</div>',
            `<div id='2' class='level_code jerry_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.oneTag,
            tags.jerry.lineBreak,
            '</div>',
        ],
        tooltipSet: [tags.jerry.tooltip, tags.jerry.tooltip, tags.jerry.tooltip],
        tagsSetName: [tags.jerry.name, tags.jerry.name, tags.jerry.name],
        picturesSetWithOutShadow: [
            tags.jerry.imageWithOutShadow,
            tags.jerry.imageWithOutShadow,
            tags.jerry.imageWithOutShadow,
        ],
        picturesSetWithShadow: [tags.jerry.imageWithShadow, tags.jerry.imageWithShadow, tags.jerry.imageWithShadow],
        pictureSetRightAnswers: ['answer', 'answer', 'answer'],
        pictureSetPossibleAnswersForAloneSelectors: ['jerry', 'jerry', 'jerry'],
        pictureSetPossibleAnswersForCombineSelectors: ['noselector', 'noselector', 'noselector'],
    },
    {
        nameOfLevel: 'Level 2',
        number: 2,
        whattodo: 'Select Tom',
        selector: 'tom',
        rightAnswer: 'tom',
        anotherPossibleAnwers: [
            'jerry ~ tom',
            'jerry + tom',
            'jerry~tom',
            'jerry+tom',
            ':nth-child(3)',
            ':nth-child(1n+3)',
            ':last-child',
            'tom:empty',
            'tom:last-child',
            'tom:only-child',
            'tom:fisrt-child',
            'tom:nth-child(1)',
            'tom:nth-child(1n)',
            'tom:nth-child(1n+1)',
            'tom:nth-child(odd)',
            'tom:nth-of-type(odd)',
            'tom:nth-of-type(1)',
            'tom:nth-of-type(1n)',
            'tom:nth-of-type(1n+1)',
        ],
        htmlBlockInnerTags: [
            tags.pillow.lineBreak,
            `<div id='0' class='level_code pillow_code parent'>`,
            tags.pillow.space,
            tags.pillow.space,
            tags.pillow.space,
            tags.pillow.space,
            tags.pillow.oneTag,
            tags.pillow.lineBreak,
            '</div>',
            `<div id='1' class='level_code jerry_code parent'>`,
            tags.pillow.space,
            tags.pillow.space,
            tags.pillow.space,
            tags.pillow.space,
            tags.jerry.oneTag,
            tags.pillow.lineBreak,
            '</div>',
            `<div id='2' class='level_code tom_code parent'>`,
            tags.pillow.space,
            tags.pillow.space,
            tags.pillow.space,
            tags.pillow.space,
            tags.tom.oneTag,
            tags.pillow.lineBreak,
            '</div>',
        ],
        tooltipSet: [tags.pillow.tooltip, tags.jerry.tooltip, tags.tom.tooltip],
        tagsSetName: [tags.pillow.name, tags.jerry.name, tags.tom.name],
        picturesSetWithOutShadow: [
            tags.pillow.imageWithOutShadow,
            tags.jerry.imageWithOutShadow,
            tags.tom.imageWithOutShadow,
        ],
        picturesSetWithShadow: [tags.pillow.imageWithShadow, tags.jerry.imageWithShadow, tags.tom.imageWithShadow],
        pictureSetRightAnswers: ['notanswer', 'notanswer', 'answer'],
        pictureSetPossibleAnswersForAloneSelectors: ['pillow', 'jerry', 'tom'],
        pictureSetPossibleAnswersForCombineSelectors: ['noselector', 'noselector', 'noselector'],
    },
    {
        nameOfLevel: 'Level 3',
        number: 3,
        whattodo: 'Select Jerry with cheese',
        selector: 'jerry',
        id: 'cheese',
        rightAnswer: '#cheese',
        anotherPossibleAnwers: [
            'jerry[id]',
            'jerry#cheese',
            'pillow ~ jerry',
            'pillow + jerry',
            'pillow~jerry',
            'pillow+jerry',
            ':nth-child(3)',
            ':nth-child(1n+3)',
            ':last-child',
            '#cheese:empty',
            'jerry:last-child',
            'jerry:nth-child(2)',
            'jerry:nth-child(1n+2)',
            'jerry:nth-child(even)',
            'jerry:nth-of-type(even)',
            'jerry:nth-of-type(2)',
            'jerry:nth-of-type(1n+2)',
            'jerry:last-of-type',
        ],
        htmlBlockInnerTags: [
            tags.jerrywithcheese.lineBreak,
            `<div id='0' class='level_code jerry_code parent'>`,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerry.oneTag,
            tags.jerrywithcheese.lineBreak,
            '</div>',
            `<div id='1' class='level_code pillow_code parent'>`,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.pillow.oneTag,
            tags.jerrywithcheese.lineBreak,
            '</div>',
            `<div id='2' class='level_code jerry_with_cheese_code parent'>`,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.space,
            tags.jerrywithcheese.oneTag,
            tags.jerrywithcheese.lineBreak,
            '</div>',
        ],
        tooltipSet: [tags.jerry.tooltip, tags.pillow.tooltip, tags.jerrywithcheese.tooltip],
        tagsSetName: [tags.jerry.name, tags.pillow.name, tags.jerrywithcheese.name],
        picturesSetWithOutShadow: [
            tags.jerry.imageWithOutShadow,
            tags.pillow.imageWithOutShadow,
            tags.jerrywithcheese.imageWithOutShadow,
        ],
        picturesSetWithShadow: [
            tags.jerry.imageWithShadow,
            tags.pillow.imageWithShadow,
            tags.jerrywithcheese.imageWithShadow,
        ],
        pictureSetRightAnswers: ['notanswer', 'notanswer', 'answer'],
        pictureSetPossibleAnswersForAloneSelectors: ['jerry', 'pillow', 'jerry'],
        pictureSetPossibleAnswersForCombineSelectors: ['noselector', 'noselector', 'noselector'],
    },
    {
        nameOfLevel: 'Level 4',
        number: 4,
        whattodo: 'Select tom on pillow',
        selector: 'tom',
        rightAnswer: 'pillow tom',
        anotherPossibleAnwers: [
            'pillow>tom',
            'pillow > tom',
            'pillow tom:last-child',
            'pillow tom:first-child',
            'pillow tom:only-child',
            'pillow tom:nth-child(odd)',
            'pillow tom:nth-child(1)',
            'pillow tom:nth-child(1n)',
            'pillow tom:nth-child(1n+1)',
            'pillow tom:last-of-type',
            'pillow tom:first-of-type',
            'pillow tom:only-of-type',
            'pillow tom:nth-of-type(odd)',
            'pillow tom:nth-of-type(1)',
            'pillow tom:nth-of-type(1n)',
            'pillow tom:nth-of-type(1n+1)',
        ],
        htmlBlockInnerTags: [
            tags.tom.lineBreak,
            `<div id='0' class='level_code tom_code parent'>`,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.oneTag,
            tags.tom.lineBreak,
            '</div>',
            `<div id='1' class='level_code pillow_code parent'>`,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.pillow.openTag,
            tags.tom.lineBreak,
            `<div id='2' class='level_code tom_code child'>`,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.oneTag,
            tags.tom.lineBreak,
            '</div>',
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.pillow.closeTag,
            tags.tom.lineBreak,
            '</div>',
            `<div id='3' class='level_code jerry_code parent'>`,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.tom.space,
            tags.jerry.oneTag,
            tags.tom.lineBreak,
            '</div>',
        ],
        tooltipSet: [tags.tom.tooltip, [tags.pillow.tooltip, tags.tom.tooltip], tags.jerry.tooltip],
        tagsSetName: [tags.tom.name, [tags.pillow.name, tags.tom.name], tags.jerry.name],
        picturesSetWithOutShadow: [
            tags.tom.imageWithOutShadow,
            [tags.pillow.imageWithOutShadow, tags.tom.imageWithOutShadow],
            tags.jerry.imageWithOutShadow,
        ],
        picturesSetWithShadow: [
            tags.tom.imageWithShadow,
            [tags.pillow.imageWithShadow, tags.tom.imageWithShadow],
            tags.jerry.imageWithShadow,
        ],
        pictureSetRightAnswers: ['notanswer', ['notanswer', 'answer'], 'notanswer'],
        pictureSetPossibleAnswersForAloneSelectors: ['tom', ['pillow', 'tom'], 'jerry'],
        pictureSetPossibleAnswersForCombineSelectors: ['noselector', ['noselector', 'noselector'], 'noselector'],
    },
    {
        nameOfLevel: 'Level 5',
        number: 5,
        whattodo: 'Select jerry in deapers on pillow',
        selector: 'jerry',
        id: 'deapers',
        rightAnswer: 'pillow #deapers',
        anotherPossibleAnwers: [
            'pillow #deapers:last-child',
            'pillow #deapers:first-child',
            'pillow #deapers:only-child',
            'pillow #deapers:nth-child(odd)',
            'pillow #deapers:nth-child(1)',
            'pillow #deapers:nth-child(1n)',
            'pillow #deapers:nth-child(1n+1)',
            'pillow #deapers:last-of-type',
            'pillow #deapers:first-of-type',
            'pillow #deapers:only-of-type',
            'pillow #deapers:nth-of-type(odd)',
            'pillow #deapers:nth-of-type(1)',
            'pillow #deapers:nth-of-type(1n)',
            'pillow #deapers:nth-of-type(1n+1)',
        ],
        htmlBlockInnerTags: [
            tags.jerryindeapers.lineBreak,
            `<div id='0' class='level_code tom_code parent'>`,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.tom.oneTag,
            tags.jerryindeapers.space,
            '</div>',
            `<div id='1' class='level_code pillow_code parent'>`,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.pillow.openTag,
            tags.jerryindeapers.lineBreak,
            `<div id='2' class='level_code jerry_in_deapers_code child'>`,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.oneTag,
            tags.jerryindeapers.lineBreak,
            '</div>',
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.pillow.closeTag,
            tags.tom.lineBreak,
            '</div>',
            `<div id='3' class='level_code jerry_in_deapers_code parent'>`,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.oneTag,
            tags.jerryindeapers.lineBreak,
            '</div>',
            `<div id='4' class='level_code pillow_code parent'>`,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.pillow.openTag,
            tags.jerryindeapers.lineBreak,
            `<div id='5' class='level_code jerry_code child'>`,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerry.oneTag,
            tags.jerryindeapers.lineBreak,
            '</div>',
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.jerryindeapers.space,
            tags.pillow.closeTag,
            tags.jerryindeapers.lineBreak,
            '</div>',
        ],
        tooltipSet: [
            tags.tom.tooltip,
            [tags.pillow.tooltip, tags.jerryindeapers.tooltip],
            tags.jerryindeapers.tooltip,
            [tags.pillow.tooltip, tags.jerry.tooltip],
        ],
        tagsSetName: [
            tags.tom.name,
            [tags.pillow.name, tags.jerryindeapers.name],
            tags.jerryindeapers.name,
            [tags.pillow.name, tags.jerry.name],
        ],
        picturesSetWithOutShadow: [
            tags.tom.imageWithOutShadow,
            [tags.pillow.imageWithOutShadow, tags.jerryindeapers.imageWithOutShadow],
            tags.jerryindeapers.imageWithOutShadow,
            [tags.pillow.imageWithOutShadow, tags.jerry.imageWithOutShadow],
        ],
        picturesSetWithShadow: [
            tags.tom.imageWithShadow,
            [tags.pillow.imageWithShadow, tags.jerryindeapers.imageWithShadow],
            tags.jerryindeapers.imageWithShadow,
            [tags.pillow.imageWithShadow, tags.jerry.imageWithShadow],
        ],
        pictureSetRightAnswers: ['notanswer', ['notanswer', 'answer'], 'notanswer', ['notanswer', 'notanswer']],
        pictureSetPossibleAnswersForAloneSelectors: [
            'tom',
            ['pillow', 'jerry, #deapers'],
            'jerry, #deapers',
            ['pillow', 'jerry'],
        ],
        pictureSetPossibleAnswersForCombineSelectors: [
            'noselector',
            ['pillow jerry', 'pillow jerry'],
            'noselector',
            ['pillow jerry', 'pillow jerry'],
        ],
    },
    {
        nameOfLevel: 'Level 6',
        number: 6,
        whattodo: 'Select small tom on pillow',
        selector: 'tom',
        id: '.small',
        rightAnswer: 'pillow .small',
        anotherPossibleAnwers: [
            'pillow .small:last-child',
            'pillow .small:first-child',
            'pillow .small:only-child',
            'pillow .small:nth-child(odd)',
            'pillow .small:nth-child(1)',
            'pillow .small:nth-child(1n)',
            'pillow .small:nth-child(1n+1)',
            'pillow .small:last-of-type',
            'pillow .small:first-of-type',
            'pillow .small:only-of-type',
            'pillow .small:nth-of-type(odd)',
            'pillow .small:nth-of-type(1)',
            'pillow .small:nth-of-type(1n)',
            'pillow .small:nth-of-type(1n+1)',
        ],
        htmlBlockInnerTags: [
            tags.tomsmall.lineBreak,
            `<div id='0' class='level_code pillow_code parent'>`,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.pillow.openTag,
            tags.tomsmall.space,
            `<div id='1' class='level_code tom_small_code child'>`,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.oneTag,
            tags.tomsmall.lineBreak,
            '</div>',
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.pillow.closeTag,
            tags.tomsmall.lineBreak,
            '</div>',
            `<div id='2' class='level_code tom_code parent'>`,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tom.oneTag,
            tags.tomsmall.lineBreak,
            '</div>',
            `<div id='3' class='level_code pillow_code parent'>`,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.pillow.openTag,
            tags.tomsmall.lineBreak,
            `<div id='4' class='level_code tom_code child'>`,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tom.oneTag,
            tags.tomsmall.lineBreak,
            '</div>',
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.pillow.closeTag,
            tags.tomsmall.lineBreak,
            '</div>',
            `<div id='5' class='level_code tom_small_code parent'>`,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.space,
            tags.tomsmall.oneTag,
            tags.tomsmall.lineBreak,
            '</div>',
        ],
        tooltipSet: [
            [tags.pillow.tooltip, tags.tomsmall.tooltip],
            tags.tom.tooltip,
            [tags.pillow.tooltip, tags.tom.tooltip],
            tags.tomsmall.tooltip,
        ],
        tagsSetName: [
            [tags.pillow.name, tags.tomsmall.name],
            tags.tom.name,
            [tags.pillow.name, tags.tom.name],
            tags.tomsmall.name,
        ],
        picturesSetWithOutShadow: [
            [tags.pillow.imageWithOutShadow, tags.tomsmall.imageWithOutShadow],
            tags.tom.imageWithOutShadow,
            [tags.pillow.imageWithOutShadow, tags.tom.imageWithOutShadow],
            tags.tomsmall.imageWithOutShadow,
        ],
        picturesSetWithShadow: [
            [tags.pillow.imageWithShadow, tags.tomsmall.imageWithShadow],
            tags.tom.imageWithShadow,
            [tags.pillow.imageWithShadow, tags.tom.imageWithShadow],
            tags.tomsmall.imageWithShadow,
        ],
        pictureSetRightAnswers: [['notanswer', 'answer'], 'notanswer', ['notanswer', 'notanswer'], 'notanswer'],
        pictureSetPossibleAnswersForAloneSelectors: [['pillow', 'tom'], 'tom', ['pillow', 'tom'], 'tom'],
        pictureSetPossibleAnswersForCombineSelectors: [
            ['pillow tom', 'pillow tom'],
            'noselector',
            ['pillow tom', 'pillow tom'],
            'noselector',
        ],
    },
    {
        nameOfLevel: 'Level 7',
        number: 7,
        whattodo: 'Select smiling tom on blue pillow',
        selector: 'tom',
        id: '#smile',
        rightAnswer: '.blue #smile',
        anotherPossibleAnwers: [
            '.blue tom',
            '.blue tom:last-child',
            '.blue tom:first-child',
            '.blue tom:only-child',
            '.blue tom:nth-child(odd)',
            '.blue tom:nth-child(1)',
            '.blue tom:nth-child(1n)',
            '.blue tom:nth-child(1n+1)',
            '.blue tom:first-of-type',
            '.blue tom:nth-of-type(odd)',
            '.blue tom:nth-of-type(1)',
            '.blue tom:nth-of-type(1n)',
            '.blue tom:nth-of-type(1n+1)',
            '.blue #smile:last-child',
            '.blue #smile:first-child',
            '.blue #smile:only-child',
            '.blue #smile:nth-child(odd)',
            '.blue #smile:nth-child(1)',
            '.blue #smile:nth-child(1n)',
            '.blue #smile:nth-child(1n+1)',
            '.blue #smile:first-of-type',
            '.blue #smile:nth-of-type(odd)',
            '.blue #smile:nth-of-type(1)',
            '.blue #smile:nth-of-type(1n)',
            '.blue #smile:nth-of-type(1n+1)',
        ],
        htmlBlockInnerTags: [
            tags.tomsmile.lineBreak,
            `<div id='0' class='level_code pillow_red_code parent'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowred.openTag,
            tags.tomsmile.space,
            `<div id='1' class='level_code tom_small_code child'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmall.oneTag,
            tags.tomsmile.lineBreak,
            '</div>',
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowred.closeTag,
            tags.tomsmile.lineBreak,
            '</div>',
            `<div id='2' class='level_code pillow_blue_code parent'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowblue.openTag,
            tags.tomsmile.space,
            `<div id='3' class='level_code tom_smile_code child'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.oneTag,
            tags.tomsmile.lineBreak,
            '</div>',
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowblue.closeTag,
            tags.tomsmile.lineBreak,
            '</div>',
            `<div id='4' class='level_code pillow_blue_code parent'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowblue.openTag,
            tags.tomsmile.lineBreak,
            `<div id='5' class='level_code jerry_small_code child'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.jerrysmall.oneTag,
            tags.tomsmile.lineBreak,
            '</div>',
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowblue.closeTag,
            tags.tomsmile.lineBreak,
            '</div>',
            `<div id='6' class='level_code pillow_red_code parent'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowred.openTag,
            tags.tomsmile.lineBreak,
            `<div id='7' class='level_code tom_smile_code child'>`,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.oneTag,
            tags.tomsmile.lineBreak,
            '</div>',
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.tomsmile.space,
            tags.pillowred.closeTag,
            tags.tomsmile.lineBreak,
            '</div>',
        ],
        tooltipSet: [
            [tags.pillowred.tooltip, tags.tomsmall.tooltip],
            [tags.pillowblue.tooltip, tags.tomsmile.tooltip],
            [tags.pillowblue.tooltip, tags.jerrysmall.tooltip],
            [tags.pillowred.tooltip, tags.tomsmile.tooltip],
        ],
        tagsSetName: [
            [tags.pillowred.name, tags.tomsmall.name],
            [tags.pillowblue.name, tags.tomsmile.name],
            [tags.pillowblue.name, tags.jerrysmall.name],
            [tags.pillowred.name, tags.tomsmile.name],
        ],
        picturesSetWithOutShadow: [
            [tags.pillowred.imageWithOutShadow, tags.tomsmall.imageWithOutShadow],
            [tags.pillowblue.imageWithOutShadow, tags.tomsmile.imageWithOutShadow],
            [tags.pillowblue.imageWithOutShadow, tags.jerrysmall.imageWithOutShadow],
            [tags.pillowred.imageWithOutShadow, tags.tomsmile.imageWithOutShadow],
        ],
        picturesSetWithShadow: [
            [tags.pillowred.imageWithShadow, tags.tomsmall.imageWithShadow],
            [tags.pillowblue.imageWithShadow, tags.tomsmile.imageWithShadow],
            [tags.pillowblue.imageWithShadow, tags.jerrysmall.imageWithShadow],
            [tags.pillowred.imageWithShadow, tags.tomsmile.imageWithShadow],
        ],
        pictureSetRightAnswers: [
            ['notanswer', 'notanswer'],
            ['notanswer', 'answer'],
            ['notanswer', 'notanswer'],
            ['notanswer', 'notanswer'],
        ],
        pictureSetPossibleAnswersForAloneSelectors: [
            ['pillow, .red, pillow.red', 'tom, .small, tom.small'],
            ['pillow, .blue, pillow.blue', 'tom, #smile, tom#smile'],
            ['pillow, .blue, pillow.blue', 'jerry, .small, jerry.small'],
            ['pillow, .red, pillow.red', 'tom, #smile, tom#smile'],
        ],
        pictureSetPossibleAnswersForCombineSelectors: [
            ['noselector', 'pillow tom, .red tom, pillow .small, .red .small'],
            ['noselector', 'pillow tom, .blue tom, pillow #smile, .blue #smile'],
            ['noselector', 'pillow jerry, .blue jerry, pillow .small, .blue .small'],
            ['noselector', 'pillow tom, .red tom, pillow #smile, .red #smile'],
        ],
    },
    {
        nameOfLevel: 'Level 8',
        number: 8,
        whattodo: 'Select small jerry on blue pillow',
        selector: 'jerry',
        id: '.small',
        rightAnswer: '.blue jerry.small',
        anotherPossibleAnwers: [
            '.blue jerry.small:first-child',
            '.blue jerry.small:last-child',
            '.blue jerry.small:only-child',
            '.blue jerry.small:nth-child(odd)',
            '.blue jerry.small:nth-child(1)',
            '.blue jerry.small:nth-child(1n)',
            '.blue jerry.small:nth-child(1n+1)',
            '.blue jerry.small:first-of-type',
            '.blue jerry.small:only-of-type',
            '.blue jerry.small:last-of-type',
            '.blue jerry.small:nth-of-type(odd)',
            '.blue jerry.small:nth-of-type(1)',
            '.blue jerry.small:nth-of-type(1n)',
            '.blue jerry.small:nth-of-type(1n+1)',
        ],
        htmlBlockInnerTags: [
            tags.jerrysmall.lineBreak,
            `<div id='0' class='level_code pillow_blue_code parent'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowblue.openTag,
            tags.jerrysmall.space,
            `<div id='1' class='level_code jerry_small_code child'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.oneTag,
            tags.jerrysmall.lineBreak,
            '</div>',
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowblue.closeTag,
            tags.jerrysmall.lineBreak,
            '</div>',
            `<div id='2' class='level_code pillow_red_code parent'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowred.openTag,
            tags.jerrysmall.space,
            `<div id='3' class='level_code jerry_small_code child'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.oneTag,
            tags.jerrysmall.lineBreak,
            '</div>',
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowred.closeTag,
            tags.jerrysmall.lineBreak,
            '</div>',
            `<div id='4' class='level_code pillow_blue_code parent'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowblue.openTag,
            tags.jerrysmall.lineBreak,
            `<div id='5' class='level_code jerry_with_cheese_code child'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrywithcheese.oneTag,
            tags.jerrysmall.lineBreak,
            '</div>',
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowblue.closeTag,
            tags.jerrysmall.lineBreak,
            '</div>',
            `<div id='6' class='level_code pillow_blue_code parent'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowblue.openTag,
            tags.jerrysmall.lineBreak,
            `<div id='7' class='level_code tom_small_code child'>`,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.tomsmall.oneTag,
            tags.jerrysmall.lineBreak,
            '</div>',
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.jerrysmall.space,
            tags.pillowblue.closeTag,
            tags.jerrysmall.lineBreak,
            '</div>',
        ],
        tooltipSet: [
            [tags.pillowblue.tooltip, tags.jerrysmall.tooltip],
            [tags.pillowred.tooltip, tags.jerrysmall.tooltip],
            [tags.pillowblue.tooltip, tags.jerrywithcheese.tooltip],
            [tags.pillowblue.tooltip, tags.tomsmall.tooltip],
        ],
        tagsSetName: [
            [tags.pillowblue.name, tags.jerrysmall.name],
            [tags.pillowred.name, tags.jerrysmall.name],
            [tags.pillowblue.name, tags.jerrywithcheese.name],
            [tags.pillowblue.name, tags.tomsmall.name],
        ],
        picturesSetWithOutShadow: [
            [tags.pillowblue.imageWithOutShadow, tags.jerrysmall.imageWithOutShadow],
            [tags.pillowred.imageWithOutShadow, tags.jerrysmall.imageWithOutShadow],
            [tags.pillowblue.imageWithOutShadow, tags.jerrywithcheese.imageWithOutShadow],
            [tags.pillowblue.imageWithOutShadow, tags.tomsmall.imageWithOutShadow],
        ],
        picturesSetWithShadow: [
            [tags.pillowblue.imageWithShadow, tags.jerrysmall.imageWithShadow],
            [tags.pillowred.imageWithShadow, tags.jerrysmall.imageWithShadow],
            [tags.pillowblue.imageWithShadow, tags.jerrywithcheese.imageWithShadow],
            [tags.pillowblue.imageWithShadow, tags.tomsmall.imageWithShadow],
        ],
        pictureSetRightAnswers: [
            ['notanswer', 'answer'],
            ['notanswer', 'notanswer'],
            ['notanswer', 'notanswer'],
            ['notanswer', 'notanswer'],
        ],
        pictureSetPossibleAnswersForAloneSelectors: [
            ['pillow, .blue, pillow.blue', 'jerry, .small, jerry.small'],
            ['pillow, .red, pillow.red', 'jerry, .small, jerry.small'],
            ['pillow, .blue, pillow.blue', 'jerry, #cheese, jerry#cheese'],
            ['pillow, .blue, pillow.blue', 'tom, .small, tom.small'],
        ],
        pictureSetPossibleAnswersForCombineSelectors: [
            ['noselector', 'pillow jerry, pillow .small, .blue jerry, .blue .small'],
            ['noselector', 'pillow jerry, .red jerry, pillow .small, .red .small'],
            ['noselector', 'pillow jerry, .blue jerry, pillow #cheese, .blue #cheese'],
            ['noselector', 'pillow tom, .blue tom, pillow .small, .blue .small'],
        ],
    },
    {
        nameOfLevel: 'Level 9',
        number: 9,
        whattodo: 'Select all Jerry mice and Tom cats',
        selector: 'jerry',
        rightAnswer: '*',
        anotherPossibleAnwers: [
            'tom,jerry',
            'tom, jerry',
            'jerry,tom',
            'jerry, tom',
            'tom ~ jerry',
            'tom~jerry',
            ':nth-child(1n+1)',
            ':nth-child(1n)',
        ],
        htmlBlockInnerTags: [
            tags.jerry.lineBreak,
            `<div id='0' class='level_code tom_angry_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.tomangry.oneTag,
            tags.jerry.lineBreak,
            '</div>',
            `<div id='1' class='level_code jerry_steals_cheese_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerrystealscheese.oneTag,
            tags.jerry.space,
            '</div>',
            `<div id='2' class='level_code tom_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.tom.oneTag,
            tags.jerry.space,
            '</div>',
            `<div id='3' class='level_code jerry_guilty_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerryguilty.oneTag,
            tags.jerry.space,
            '</div>',
            `<div id='4' class='level_code jerry_triangle_code parent'>`,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerry.space,
            tags.jerrytriangle.oneTag,
            tags.jerry.space,
            '</div>',
        ],
        tooltipSet: [
            tags.tomangry.tooltip,
            tags.jerrystealscheese.tooltip,
            tags.tom.tooltip,
            tags.jerryguilty.tooltip,
            tags.jerrytriangle.tooltip,
        ],
        tagsSetName: [
            tags.tomangry.name,
            tags.jerrystealscheese.name,
            tags.tom.name,
            tags.jerryguilty.name,
            tags.jerrytriangle.name,
        ],
        picturesSetWithOutShadow: [
            tags.tomangry.imageWithOutShadow,
            tags.jerrystealscheese.imageWithOutShadow,
            tags.tom.imageWithOutShadow,
            tags.jerryguilty.imageWithOutShadow,
            tags.jerrytriangle.imageWithOutShadow,
        ],
        picturesSetWithShadow: [
            tags.tomangry.imageWithShadow,
            tags.jerrystealscheese.imageWithShadow,
            tags.tom.imageWithShadow,
            tags.jerryguilty.imageWithShadow,
            tags.jerrytriangle.imageWithShadow,
        ],
        pictureSetRightAnswers: ['answer', 'answer', 'answer', 'answer', 'answer'],
        pictureSetPossibleAnswersForAloneSelectors: [
            'tom, #angry, tom#angry',
            'jerry, #steals, jerry#steals',
            'tom',
            'jerry, #guilty, jerry#guilty',
            'jerry, #triangle, jerry#triangle',
        ],
        pictureSetPossibleAnswersForCombineSelectors: [
            'noselector',
            'noselector',
            'noselector',
            'noselector',
            'noselector',
        ],
    },
    {
        nameOfLevel: 'Level 10',
        number: 10,
        whattodo: 'Select all Jerry mice and Tom cats on pillows',
        selector: 'jerry',
        rightAnswer: 'pillow *',
        anotherPossibleAnwers: [
            'pillow tom, pillow tom&jerry',
            'pillow jerry:first-child, pillow tom&jerry:first-child',
            'pillow jerry:last-child, pillow tom&jerry:last-child',
            'pillow jerry:first-child, pillow tom&jerry:last-child',
            'pillow jerry:last-child, pillow tom&jerry:first-child',
            'pillow jerry:only-child, pillow tom&jerry:only-child',
            'pillow jerry:nth-child(odd), pillow tom&jerry:nth-child(odd)',
            'pillow jerry:nth-child(1), pillow tom&jerry:nth-child(1)',
            'pillow jerry:nth-child(1n), pillow tom&jerry:nth-child(1n)',
            'pillow jerry:nth-child(1n+1), pillow tom&jerry:nth-child(1n+1)',
            'pillow jerry:only-of-type, pillow tom&jerry:only-of-type',
            'pillow jerry:nth-of-type(1), pillow tom&jerry:nth-of-type(1)',
            'pillow jerry:nth-of-type(1n), pillow tom&jerry:nth-of-type(1n)',
            'pillow jerry:nth-of-type(1n+1), pillow tom&jerry:nth-of-type(1n+1)',
            'pillow jerry:nth-of-type(odd), pillow tom&jerry:nth-of-type(odd)',
        ],
        htmlBlockInnerTags: [
            tags.jerrybye.lineBreak,
            `<div id='0' class='level_code pillow_blue_code parent'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowblue.openTag,
            tags.jerrybye.space,
            `<div id='1' class='level_code jerry_bye_code child'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.oneTag,
            tags.jerrybye.lineBreak,
            '</div>',
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowblue.closeTag,
            tags.jerrybye.lineBreak,
            '</div>',
            `<div id='2' class='level_code pillow_red_code parent'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowred.openTag,
            tags.jerrybye.space,
            `<div id='3' class='level_code tom_jerry_code child'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.tomandjerry.oneTag,
            tags.jerrybye.lineBreak,
            '</div>',
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowred.closeTag,
            tags.jerrybye.lineBreak,
            '</div>',
            `<div id='4' class='level_code pillow_blue_code parent'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowblue.openTag,
            tags.jerrybye.lineBreak,
            `<div id='5' class='level_code tom_jerry_suit_code child'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.tomandjerrysuit.oneTag,
            tags.jerrybye.lineBreak,
            '</div>',
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowblue.closeTag,
            tags.jerrybye.lineBreak,
            '</div>',
            `<div id='6' class='level_code pillow_red_code parent'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowred.openTag,
            tags.jerrybye.lineBreak,
            `<div id='7' class='level_code jerry_surprise_code child'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrysurprise.oneTag,
            tags.jerrybye.lineBreak,
            '</div>',
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowred.closeTag,
            tags.jerrybye.lineBreak,
            '</div>',
            `<div id='8' class='level_code pillow_blue_code parent'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowblue.openTag,
            tags.jerrybye.lineBreak,
            `<div id='9' class='level_code tom_jerry_catch_code child'>`,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.tomandjerrycatch.oneTag,
            tags.jerrybye.lineBreak,
            '</div>',
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.jerrybye.space,
            tags.pillowblue.closeTag,
            tags.jerrybye.lineBreak,
            '</div>',
        ],
        tooltipSet: [
            [tags.pillowblue.tooltip, tags.jerrybye.tooltip],
            [tags.pillowred.tooltip, tags.tomandjerry.tooltip],
            [tags.pillowblue.tooltip, tags.tomandjerrysuit.tooltip],
            [tags.pillowred.tooltip, tags.jerrysurprise.tooltip],
            [tags.pillowblue.tooltip, tags.tomandjerrycatch.tooltip],
        ],
        tagsSetName: [
            [tags.pillowblue.name, tags.jerrybye.name],
            [tags.pillowred.name, tags.tomandjerry.name],
            [tags.pillowblue.name, tags.tomandjerrysuit.name],
            [tags.pillowred.name, tags.jerrysurprise.name],
            [tags.pillowblue.name, tags.tomandjerrycatch.name],
        ],
        picturesSetWithOutShadow: [
            [tags.pillowblue.imageWithOutShadow, tags.jerrybye.imageWithOutShadow],
            [tags.pillowred.imageWithOutShadow, tags.tomandjerry.imageWithOutShadow],
            [tags.pillowblue.imageWithOutShadow, tags.tomandjerrysuit.imageWithOutShadow],
            [tags.pillowred.imageWithOutShadow, tags.jerrysurprise.imageWithOutShadow],
            [tags.pillowblue.imageWithOutShadow, tags.tomandjerrycatch.imageWithOutShadow],
        ],
        picturesSetWithShadow: [
            [tags.pillowblue.imageWithShadow, tags.jerrybye.imageWithShadow],
            [tags.pillowred.imageWithShadow, tags.tomandjerry.imageWithShadow],
            [tags.pillowblue.imageWithShadow, tags.tomandjerrysuit.imageWithShadow],
            [tags.pillowred.imageWithShadow, tags.jerrysurprise.imageWithShadow],
            [tags.pillowblue.imageWithShadow, tags.tomandjerrycatch.imageWithShadow],
        ],
        pictureSetRightAnswers: [
            ['notanswer', 'answer'],
            ['notanswer', 'answer'],
            ['notanswer', 'answer'],
            ['notanswer', 'answer'],
            ['notanswer', 'answer'],
        ],
        pictureSetPossibleAnswersForAloneSelectors: [
            ['pillow, .blue, pillow.blue', 'jerry, #bye, jerry #bye'],
            ['pillow, .red, pillow.red', 'tom&jerry'],
            ['pillow, .blue, pillow.blue', 'tom&jerry, #suit, tom&jerry #suit'],
            ['pillow, .red, pillow.red', 'jerry, #surprise, jerry #surprise'],
            ['pillow, .blue, pillow.blue', 'tom&jerry, #catch, tom&jerry #catch'],
        ],
        pictureSetPossibleAnswersForCombineSelectors: [
            ['noselector', 'pillow jerry, pillow #bye, .blue jerry, .blue #bye'],
            ['noselector', 'pillow tom&jerry, .red tom&jerry'],
            ['noselector', 'pillow tom&jerry, .blue tom&jerry, pillow #suit, .blue #suit'],
            ['noselector', 'pillow jerry, pillow #surprise, .red jerry, .red #surprise'],
            ['noselector', 'pillow tom&jerry, .blue tom&jerry, pillow #catch, .blue #catch'],
        ],
    },
];

export default levels;
