import { TTags } from '../../types';
const tags: TTags = {
    pillow: {
        name: 'pillow',
        tooltip: `&lt;pillow&gt;&lt;/pillow&gt;`,
        openTag: `&lt;pillow&gt;`,
        closeTag: `&lt;/pillow&gt;`,
        oneTag: `&lt;pillow /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/pillow.png',
        imageWithShadow: './assets/icons/pillowshadow.png',
    },
    jerry: {
        name: 'jerry',
        tooltip: `&lt;jerry&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerry.png',
        imageWithShadow: './assets/icons/jerryshadow.png',
    },
    tom: {
        name: 'tom',
        tooltip: `&lt;tom&gt;&lt;/tom&gt;`,
        openTag: `&lt;tom&gt;`,
        closeTag: `&lt;/tom&gt;`,
        oneTag: `&lt;tom /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/tom.png',
        imageWithShadow: './assets/icons/tomshadow.png',
    },
    jerrywithcheese: {
        name: 'jerry with cheese',
        tooltip: `&lt;jerry id='cheese'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry id='cheese'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry id='cheese' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerrywithcheese.png',
        imageWithShadow: './assets/icons/jerrywithcheeseshadow.png',
    },
    jerryindeapers: {
        name: 'jerry in deapers',
        tooltip: `&lt;jerry id='deapers'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry id='deapers'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry id='deapers' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerryindeapers.png',
        imageWithShadow: './assets/icons/jerryindeapersshadow.png',
    },
    jerrystealscheese: {
        name: 'jerry steals cheese',
        tooltip: `&lt;jerry id='steals'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry id='steals'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry id='steals' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerrystolecheese.png',
        imageWithShadow: './assets/icons/jerrystolecheeseshadow.png',
    },
    jerrytriangle: {
        name: 'jerry triangle',
        tooltip: `&lt;jerry class='triangle'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry class='triangle'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry class='triangle' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerrytriangle.png',
        imageWithShadow: './assets/icons/jerrytriangleshadow.png',
    },
    jerryguilty: {
        name: 'jerry guilty',
        tooltip: `&lt;jerry id='guilty'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry id='guilty'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry id='guilty' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerryguilty.png',
        imageWithShadow: './assets/icons/jerryguiltyshadow.png',
    },
    jerrybye: {
        name: 'jerry bye',
        tooltip: `&lt;jerry id='bye'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry id='bye'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry id='bye' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerrybye.png',
        imageWithShadow: './assets/icons/jerrybyeshadow.png',
    },
    jerrysurprise: {
        name: 'jerry surprise',
        tooltip: `&lt;jerry id='surprise'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry id='surprise'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry id='surprise' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerrysurprise.png',
        imageWithShadow: './assets/icons/jerrysurpriseshadow.png',
    },
    jerrysmall: {
        name: 'jerry small',
        tooltip: `&lt;jerry class='small'&gt;&lt;/jerry&gt;`,
        openTag: `&lt;jerry class='small'&gt;`,
        closeTag: `&lt;/jerry&gt;`,
        oneTag: `&lt;jerry class='small' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/jerrysmall.png',
        imageWithShadow: './assets/icons/jerrysmallshadow.png',
    },
    tomsmall: {
        name: 'tom small',
        tooltip: `&lt;tom class='small'&gt;&lt;/tom&gt;`,
        openTag: `&lt;tom class='small'&gt;`,
        closeTag: `&lt;/tom&gt;`,
        oneTag: `&lt;tom class='small' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/smalltom.png',
        imageWithShadow: './assets/icons/smalltomshadow.png',
    },
    tomsmile: {
        name: 'tom smile',
        tooltip: `&lt;tom id='smile'&gt;&lt;/tom&gt;`,
        openTag: `&lt;tom id='smile'&gt;`,
        closeTag: `&lt;/tom&gt;`,
        oneTag: `&lt;tom id='smile' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/tomfunny.png',
        imageWithShadow: './assets/icons/tomfunnyshadow.png',
    },
    tomangry: {
        name: 'tom angry',
        tooltip: `&lt;tom id='angry'&gt;&lt;/tom&gt;`,
        openTag: `&lt;tom id='angry'&gt;`,
        closeTag: `&lt;/tom&gt;`,
        oneTag: `&lt;tom id='angry' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/angrytom.png',
        imageWithShadow: './assets/icons/angrytomshadow.png',
    },
    tomandjerry: {
        name: 'tom and jerry',
        tooltip: `&lt;tom&amp;jerry&gt;&lt;/tom&amp;jerry&gt;`,
        openTag: `&lt;tom&amp;jerry&gt;`,
        closeTag: `&lt;/tom&amp;jerry&gt;`,
        oneTag: `&lt;tom&amp;jerry /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/tomjerry.png',
        imageWithShadow: './assets/icons/tomjerryshadow.png',
    },
    tomandjerrysuit: {
        name: 'tom and jerry in suit',
        tooltip: `&lt;tom&amp;jerry id='suit'&gt;&lt;/tom&amp;jerry&gt;`,
        openTag: `&lt;tom&amp;jerry id='suit'&gt;`,
        closeTag: `&lt;/tom&amp;jerry&gt;`,
        oneTag: `&lt;tom&amp;jerry id='suit' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/tomjerrysuit.png',
        imageWithShadow: './assets/icons/tomjerrysuitshadow.png',
    },
    tomandjerrycatch: {
        name: 'tom and jerry catch',
        tooltip: `&lt;tom&amp;jerry id='catch'&gt;&lt;/tom&amp;jerry&gt;`,
        openTag: `&lt;tom&amp;jerry id='catch'&gt;`,
        closeTag: `&lt;/tom&amp;jerry&gt;`,
        oneTag: `&lt;tom&amp;jerry id='catch' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/tomjerrycatch.png',
        imageWithShadow: './assets/icons/tomjerrycatchshadow.png',
    },
    pillowblue: {
        name: 'pillow blue',
        tooltip: `&lt;pillow class='blue'&gt;&lt;/pillow&gt;`,
        openTag: `&lt;pillow class='blue'&gt;`,
        closeTag: `&lt;/pillow&gt;`,
        oneTag: `&lt;pillow id='blue' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/pillow2.png',
        imageWithShadow: './assets/icons/pillow2shadow.png',
    },
    pillowred: {
        name: 'pillow red',
        tooltip: `&lt;pillow class='red'&gt;&lt;/pillow&gt;`,
        openTag: `&lt;pillow class='red'&gt;`,
        closeTag: `&lt;/pillow&gt;`,
        oneTag: `&lt;pillow class='red' /&gt;`,
        space: '&nbsp;',
        lineBreak: '<br>',
        imageWithOutShadow: './assets/icons/pillow.png',
        imageWithShadow: './assets/icons/pillowshadow.png',
    },
};

export default tags;
